<%@ page import="java.util.List, Model.Reports, java.text.SimpleDateFormat" %>

<h2 class="mb-3 border-bottom pb-2 text-body"><i class="fas fa-file-alt"></i> View Reports</h2>

<!-- Generate Report Form -->
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title"><i class="fas fa-plus"></i> Generate New Report</h5>
        <form class="row g-3" id="reportForm">
            <div class="col-md-4">
                <label for="startDate" class="form-label">Start Date</label>
                <input type="date" class="form-control" id="startDate" name="startDate" required>
            </div>
            <div class="col-md-4">
                <label for="endDate" class="form-label">End Date</label>
                <input type="date" class="form-control" id="endDate" name="endDate" required>
            </div>
            <div class="col-md-4 d-flex align-items-end">
                <button type="button" class="btn btn-primary" onclick="generateReport()">
                    <i class="fas fa-cogs"></i> Generate Sales Report
                </button>
            </div>
        </form>
    </div>
</div>

<!-- Table Content -->
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered align-middle">
        <thead class="table-light">
            <tr>
                <th>Report ID</th>
                <th>Report Type</th>
                <th>Generated Date</th>
                <th>Generated By</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% 
            List<Reports> reports = (List<Reports>) request.getAttribute("reportList");
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            if (reports != null && !reports.isEmpty()) {
                for (Reports report : reports) {
            %>
            <tr>
                <td><%= report.getId() %></td>
                <td><%= report.getReportType() %></td>
                <td><%= dateFormat.format(report.getGeneratedDate()) %></td>
                <td>
                    <%= report.getGeneratedById() != null ? 
                        report.getGeneratedById().getUsername() : "System" %>
                </td>
                <td>
                    <button class="btn btn-sm btn-success" 
                            onclick="showReport(<%= report.getId() %>, `<%= report.getDetails().replace("`", "\\`") %>`)"
                            title="View Details">
                        <i class="fas fa-eye"></i>
                    </button>
                    <form method="post" action="${pageContext.request.contextPath}/admin/reports" style="display:inline;">
                        <input type="hidden" name="action" value="delete">
                        <input type="hidden" name="id" value="<%= report.getId() %>">
                        <button type="submit" class="btn btn-sm btn-danger" title="Delete Report">
                            <i class="fas fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
            <% 
                }
            } else {
            %>
            <tr>
                <td colspan="5" class="text-center">No reports available</td>
            </tr>
            <% } %>
        </tbody>
    </table>
</div>

<!-- Report Details Modal -->
<div class="modal fade" id="reportModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Report Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <pre id="reportDetails" class="report-content"></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<style>
.report-content {
    white-space: pre-wrap;
    font-family: inherit;
    background: none;
    border: none;
    padding: 0;
    margin: 0;
}
</style>

<script>
// Add generate report function
function generateReport() {
    const startDate = document.getElementById('startDate').value;
    const endDate = document.getElementById('endDate').value;
    
    if (!startDate || !endDate) {
        Swal.fire({
            title: 'Error!',
            text: 'Please select both start and end dates',
            icon: 'error'
        });
        return;
    }
    
    if (new Date(endDate) < new Date(startDate)) {
        Swal.fire({
            title: 'Error!',
            text: 'End date must be after start date',
            icon: 'error'
        });
        return;
    }
    
    window.location.href = '${pageContext.request.contextPath}/admin/reports?action=generate&startDate=' + 
        encodeURIComponent(startDate) + '&endDate=' + encodeURIComponent(endDate);
}

// Keep existing show report function and message display code
function showReport(id, details) {
    document.getElementById('reportDetails').textContent = details;
    new bootstrap.Modal(document.getElementById('reportModal')).show();
}

// Display success/error messages if present
<% if (request.getSession().getAttribute("success") != null) { %>
    Swal.fire({
        icon: 'success',
        title: 'Success',
        text: '<%= request.getSession().getAttribute("success") %>',
        timer: 3000
    });
    <% request.getSession().removeAttribute("success"); %>
<% } %>

<% if (request.getSession().getAttribute("error") != null) { %>
    Swal.fire({
        icon: 'error',
        title: 'Error',
        text: '<%= request.getSession().getAttribute("error") %>'
    });
    <% request.getSession().removeAttribute("error"); %>
<% } %>
</script>